---
version: '3'
 
networks:
  loki:
 
services:
  loki:
    image: grafana/loki
    volumes:
      - ./config/loki.config.yaml:/etc/loki/loki.config.yaml
      - ./loki-rules:/loki/rules
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki.config.yaml  
    networks:
      - loki
 
  promtail:
    image: grafana/promtail
    volumes:
      - ./config/promtail.config.yaml:/etc/promtail/promtail.config.yaml
      - ./logs:/logs
    command: -config.file=/etc/promtail/promtail.config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - loki
 
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager.config.yaml:/etc/alertmanager/alertmanager.config.yaml
    command: --config.file=/etc/alertmanager/alertmanager.config.yaml
    networks:
      - loki
 
  # Test webhook for alertmanager:
  webhook:
    image: alpine
    ports:
      - 8080:8080
    entrypoint: /bin/sh
    command: 
      - -c
      - nc -l -p 8080
    networks:
      - loki
