---
global:
  resolve_timeout: 5m

route:
  group_by:
    - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: default

# inhibit_rules:
#   - source_matchers:
#       - 'severity = critical'
#     target_matchers:
#       - 'severity = warning'
#     equal:
#       - alertname
#       - instance

receivers:
  - name: default
    webhook_configs:
      - url: http://webhook:8080
